### ISSUE TITLE
CCS1 hangs with more than 4 processes

### ISSUE THREAD

**Issue by kshedstrom** [ESMG/MOM6#9]
It is hanging at line 657 of MOM_open_boundary.F90:
call pass_vector(OBC%eta_outer_u,OBC%eta_outer_v,G%Domain, To_All+SCALAR_PAIR, CGRID_NE)

Looks like the two tiles without an open boundary are doing something else:
![hung_job](https://cloud.githubusercontent.com/assets/444446/16309441/3553ed3a-3915-11e6-9d50-b3d34e1e7232.png)

**Comment by adcroft** [comment]
That's because an mpp_update needs all PEs to have a valid array and call.
We (I) deallocated the arrays on some PEs based on how the "simple" OBCs
were written. Evidently for Flather we need to not deallocate anywhere. I
added this deallocation in one of my last PRs to your branch. It's curious
that my own tests passed so the layout must have happened to have an OB on
every PE.

**Comment by kshedstrom** [comment]
If we can't deallocate OBC, then we'll have to change these checks:
```
if (.not.associated(OBC)) return
```
